// Actually putting an interface in this project was great put it doesn't deserved my time :)
public class Main {
	public static void main(String[] ags)
	{
		// To be done
	}
	
	/* **********************************************************************
	 * first and last name in ==> first(Capitalized) + last(Capitalized) out*
	 * this function does the formatting inplace							*
	 ***********************************************************************/
	static String fullName(String first_name, String last_name)
	{
		// removing all whitespaces (regex generated by chat-gpt :))
		first_name = first_name.replaceAll("^\\s+|\\s+$", "");
		last_name = last_name.replaceAll("^\\s+|\\s+$", "");

		// Capitalizing first letter of first name
        if (!first_name.isEmpty()) {
            first_name = first_name.substring(0, 1).toUpperCase() + first_name.substring(1).toLowerCase();
        }

        // Capitalizing first letter of last name
        if (!last_name.isEmpty()) {
            last_name = last_name.substring(0, 1).toUpperCase() + last_name.substring(1).toLowerCase();
        }

        return first_name + " " + last_name;
	}
}
