import java.util.ArrayList;
import java.util.Scanner;

// Actually putting an interface in this project was great put it doesn't deserved my time :)
public class Main {
	public static void main(String[] ags)
	{
		// to be done
	}
	
	/* **********************************************************************
	 * first and last name in ==> first(Capitalized) + last(Capitalized) out*
	 * this function does the formatting inplace							*
	 ***********************************************************************/
	static String fullName(String first_name, String last_name)
	{
		// removing all whitespaces (regex generated by chat-gpt :))
		first_name = first_name.replaceAll("^\\s+|\\s+$", "");
		last_name = last_name.replaceAll("^\\s+|\\s+$", "");

		// Capitalizing first letter of first name
        if (!first_name.isEmpty()) {
            first_name = first_name.substring(0, 1).toUpperCase() + first_name.substring(1).toLowerCase();
        }

        // Capitalizing first letter of last name
        if (!last_name.isEmpty()) {
            last_name = last_name.substring(0, 1).toUpperCase() + last_name.substring(1).toLowerCase();
        }

        return first_name + " " + last_name;
	}

	/* **********************************************************************
	 * phone-number in ==> the phone-number if it was valid else null		*
	 ***********************************************************************/
	 static String phoneNumber(String number)
	 {
		// removing all whitespaces (regex generated by chat-gpt :))
		number = number.replaceAll("^\\s+|\\s+$", "");
	 	
		if (!number.matches("\\d+"))
			return null;

		if (number.length() == 10)
		{
			if (number.charAt(0) == '9')
				return "0" + number;
		}
		
		if (number.length() == 11)
		{
			if (number.charAt(0) == '0' && number.charAt(1) == '9')
				return number;
		}

		return null;
	 }

	/* **********************************************************************
	 * user-id in ==> the id if it was valid else null						*
	 ***********************************************************************/
	 static String userId(String id)
	 {
		// removing all whitespaces (regex generated by chat-gpt :))
		id = id.replaceAll("^\\s+|\\s+$", "");

		if (!id.matches("\\d+") || id.length() < 4 || id.length() > 13)
			return null;

		return id;
	 }

	/* **********************************************************************
	 * getting interests of user one by one ==> a list of user intersts		*
	 ***********************************************************************/
	 static ArrayList<String> getInterests()
	 {
	 	System.out.println("--~~Enter your intersts. type '!' if it's done. (max: 10)~~-");

		Scanner s = new Scanner(System.in);
		ArrayList<String> result = new ArrayList<>();
		String input = null;
		int count = 1;
		while (count < 11)
		{
			System.out.print(count + ". ");
			input = s.nextLine().replaceAll("^\\s+|\\s+$", "");

			if (input.isEmpty())
			{
				System.out.println("Please enter something!");
				continue;
			}
			
			if (result.contains(input))
			{
				System.out.println("You entered this once before!");
				continue;
			}

			if (input.equals("!"))
			{
				return result; 
			}

			result.add(input);
			count++;
		}
		s.close();
		return result;
	 }

	/* **********************************************************************
	 * geting informations of user ==> printing out the formatted version	*
	 ***********************************************************************/
	 static void userFullInformation(String fullname, String phonenumber, String userid, ArrayList<String> interests)
	 {
	 	System.out.println("~~Your resume:");
		System.out.printf("##Hello! My name is %s. My ID is %s.", fullname, userid);
		if (interests.isEmpty())
		{
			System.out.print("\n##Actally I have no interests, cause I think everything is boring :)\n");
		}
		else
		{
			System.out.print(" Here are some of my interests:\n");
			for (int i = 0; i < interests.size(); i++)
			{
				System.out.println("## " + (i + 1) + ". " + interests.get(i));
			}
		}
		System.out.println("##You can reach me Via my phone number " + phonenumber + ".");
	 }
}
